# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dee72936c86eafb0415c369b00ff769d01c9c4c9262d35a0f6bac0e296da178f0fb85d28fb63ba0f34556558d91b9788892c59a962df2042cd3254da6a46727

test:
  secret_key_base: 6cf4c7365ec96d12ceda28f3510130c0a4519a718e49223eed7052bc01840330da2dfb6dc328ed5982824745ea7e6ffdc21a28bb74085874fcc88bee87323870

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 152e430721617d9261573969235b051929e0b907765604040073f71bb69fcad8fba83041e594ef1ff7716ccc5f91c88b24a847f8014d2bd12a55aaf6dd3b0245
